# Generated by Django 3.0.5 on 2020-04-18 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_created_at'),
        ('Url', '0002_auto_20200417_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='full_url',
            new_name='full',
        ),
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='short',
            field=models.CharField(default='zEU', max_length=255, verbose_name='Коротная ссылка'),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='User.User', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='IP адрес')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата клика')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('referer', models.CharField(blank=True, max_length=255, verbose_name='Referer')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='Url.Url', verbose_name='Ссылка')),
            ],
            options={
                'ordering': ['click_date'],
            },
        ),
    ]
