# Generated by Django 3.0.5 on 2020-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0003_auto_20200418_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Коротная ссылка'),
        ),
    ]
